{% set name = "xarray-spatial" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 04ed5992eed25ad4d4a5277c73c1b64a3f677f179863e269fcdb199d26bcc2ea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - xrspatial = xrspatial.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - python-build
    - param
    - pyct-core
    - setuptools >=54.1.2
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - datashader >=0.15.0
    - numba
    - xarray
    - numpy

test:
  imports:
    - xrspatial
  commands:
    - pip check
    - xrspatial --help
  requires:
    - pip
    - python {{ python_min }}
    - dask
    - pyarrow

about:
  home: https://pypi.org/project/xarray-spatial/
  summary: xarray-based spatial analysis tools
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - brendancol
    - giancastro
    - ianthomas23
    - ocefpaf
    - thuydotm
