{% set python_min = "3.12" %}

{% set name = "xarray-spatial" %}
{% set version = "0.10.18" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a3db9c28b7ab3cc17ab67caeb0facb4cc6a2a5d74990757b1127ee5ab3a55514

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - xrspatial = xrspatial.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - python-build
    - param
    - pyct-core
    - setuptools >=54.1.2
    - setuptools-scm
    - pip
  run:
    - pandas >=2.2
    - urllib3 >=2.7
    - matplotlib-base
    - zstandard
    - scipy >=1.11.2
    - python >={{ python_min }}
    - datashader >=0.15.0
    - numba >=0.59
    - xarray >=2025.11
    - numpy >=1.26,<2.5

test:
  imports:
    - xrspatial
  commands:
    - pip check
    - xrspatial --help
  requires:
    - pip
    - python {{ python_min }}
    - dask
    - pyarrow

about:
  home: https://pypi.org/project/xarray-spatial/
  summary: xarray-based spatial analysis tools
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - brendancol
    - giancastro
    - ianthomas23
    - ocefpaf
    - thuydotm
