{% set name = "xarray-spatial" %}
{% set version = "0.3.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd7e3b447236f6e8f8c5110684a7ca50f97149c806f56ebf4ed1eeef1dd681ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - xrspatial = xrspatial.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
    - pyct-core
    - param
  run:
    - python >=3.7
    - dask-core
    - datashader
    - numpy <=1.23.4
    - noise >=1.2.2
    - numba
    - pyct-core
    - requests
    - scipy
    - xarray

test:
  imports:
    - xrspatial
  commands:
    - pip check
    - xrspatial --help
  requires:
    - pip

about:
  home: https://pypi.org/project/xarray-spatial/
  summary: xarray-based spatial analysis tools
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - brendancol
    - giancastro
    - ianthomas23
    - ocefpaf
    - thuydotm
